EntityFrameworkDBFirst/EntityFrameworkDBFirst/Controllers/BrandController.cs
using EntityFrameworkDBFirst.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntityFrameworkDBFirst.Controllers
{
    public class BrandController : Controller
    {
        // GET: Brand
        public ActionResult Index()
        {
            EFDBFirstDatabaseEntities eFDBFirstDatabaseEntities = new EFDBFirstDatabaseEntities();
            List<Brand> brands = eFDBFirstDatabaseEntities.Brands.ToList();

            return View(brands);
        }
    }
}

EntityFrameworkDBFirst/EntityFrameworkDBFirst/Controllers/ProductController.cs
using EntityFrameworkDBFirst.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntityFrameworkDBFirst.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index(string productName = "")
        {
            EFDBFirstDatabaseEntities eFDBFirstDatabaseEntities = new EFDBFirstDatabaseEntities();
            List<Product> products = eFDBFirstDatabaseEntities.Products.Where(u=>u.ProductName.Contains(productName)).ToList();

            ViewBag.Search = productName;

            return View(products);
        }

        public ActionResult Details(int id)
        {
            EFDBFirstDatabaseEntities eFDBFirstDatabaseEntities = new EFDBFirstDatabaseEntities();
            Product product = eFDBFirstDatabaseEntities.Products.Where(u => u.ProductID == id).FirstOrDefault();
            return View(product);
        }

        [HttpGet]
        public ActionResult Create()
        {
            List<Category> categories = new EFDBFirstDatabaseEntities().Categories.ToList();
            ViewBag.Categories = new SelectList(categories, "CategoryID", "CategoryName");

            List<Brand> brands = new EFDBFirstDatabaseEntities().Brands.ToList();
            ViewBag.Brands = new SelectList(brands, "BrandID", "BrandName");

            return View();
        }

        [HttpPost]
        public ActionResult Create(Product product)
        {
            EFDBFirstDatabaseEntities eFDBFirstDatabaseEntities = new EFDBFirstDatabaseEntities();
            eFDBFirstDatabaseEntities.Products.Add(product);
            eFDBFirstDatabaseEntities.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            EFDBFirstDatabaseEntities eFDBFirstDatabaseEntities = new EFDBFirstDatabaseEntities();
            Product product = eFDBFirstDatabaseEntities.Products.Where(u => u.ProductID == id).FirstOrDefault();
            eFDBFirstDatabaseEntities.Products.Remove(product);
            eFDBFirstDatabaseEntities.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            EFDBFirstDatabaseEntities eFDBFirstDatabaseEntities = new EFDBFirstDatabaseEntities();
            Product product = eFDBFirstDatabaseEntities.Products.Where(u => u.ProductID == id).FirstOrDefault();

            List<Category> categories = new EFDBFirstDatabaseEntities().Categories.ToList();
            ViewBag.Categories = new SelectList(categories, "CategoryID", "CategoryName");

            List<Brand> brands = new EFDBFirstDatabaseEntities().Brands.ToList();
            ViewBag.Brands = new SelectList(brands, "BrandID", "BrandName");

            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            EFDBFirstDatabaseEntities eFDBFirstDatabaseEntities = new EFDBFirstDatabaseEntities();
            
            Product existingProduct = eFDBFirstDatabaseEntities.Products.Where(u => u.ProductID == product.ProductID).FirstOrDefault();
            existingProduct.ProductName = product.ProductName;
            existingProduct.Price = product.Price;
            existingProduct.DateOfPurchase = product.DateOfPurchase;
            existingProduct.AvailabilityStatus = product.AvailabilityStatus;
            existingProduct.CategoryID = product.CategoryID;
            existingProduct.BrandID = product.BrandID;
            existingProduct.Active = product.Active;

            eFDBFirstDatabaseEntities.SaveChanges();

            return View(existingProduct);
        }
    }
}

EntityFrameworkDBFirst/EntityFrameworkDBFirst/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("head", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">MyBrand</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav me-auto">
                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                @Html.ActionLink("Brands", "Index", "Brand", null, new { @class = "nav-link" })
                @Html.ActionLink("Category", "Index", "Category", null, new { @class = "nav-link" })
                @Html.ActionLink("Products", "Index", "Product", null, new { @class = "nav-link" })
            </div>
        </div>
        </nav>
    @RenderBody()
</body>
</html>